export const GET_CITY_LOADING = "GET_CITY_LOADING";
export const GET_CITY_WEATHER_FAIL = "GET_CITY_WEATHER_FAIL";
export const GET_CITY_WEATHER_SUCCESS = "GET_CITY_WEATHER_SUCCESS";
export const REMOVE_CITY = "REMOVE_CITY";
